version: '3'
volumes:
  kei-geoserver-data:

services:
  db:
    container_name: kei-db
    restart: always
    build:
      context: ./doc/docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./doc/database:/database:ro
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    ports:
      - 15432:5432
      - 18080:8080

  geoserver:
    container_name: kei-geoserver
    restart: always
    image: gaia3d/geoserver:kei-2.16.4
#    build:
#      context: ./doc/docker/geoserver
#      dockerfile: Dockerfile
    volumes:
      - kei-geoserver-data:/geoserver-data
    network_mode: "service:db"

  rabbitmq:
    container_name: kei-rabbitmq
    restart: always
    image: gaia3d/rabbitmq:kei-3.8.9
#    build:
#      context: ./doc/docker/rabbitmq
#      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
